### PR TITLE
Hide API secret keys in Travis

### PR DESCRIPTION
**Pull request by platisd**
An example on how to build an (open source) Android application with TravisCI.

Since we need to protect the API keys, we cannot version control them but need
to somehow provide them to the CI machine. We achieve this by editing them in
`gradle.properties` during the CI build.

### CODE REVIEW

**Comment by NiklasMoller** [comment]
@platisd Need to fetch the API key from my AndroidManifext.xml like this
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/fetch_api_key_from_xml"/>

Tried inserting this into build.gradle without success:
resValue 'string', 'fetch_api_key_from_xml', GoogleAPIKey

How would I reach it from the xml file with your setup?

**Comment by platisd** [comment]
Why do you want to fetch it from your Android Manifest and not via the gradle.properties?

The Android manifest is generally supposed to be shared and it is included in clear text inside apk's which makes it a very bad place to hide something secret.

**Comment by NiklasMoller** [comment]
I resolved it - was just a typo in the instructions (Goolge instead of Google). I didn't want to expose it in AndroidManifest, just get a reference to the actual key so it can build. Now, everything compiles and run.

**Comment by NiklasMoller** [comment]
_To achieve that you need to create a copy of `gradle.properties.no.git` 
in the same directory and name it `gradle.properties`. Then you can insert in the newly created `gradle.properties`
your secret API keys without having to version control them._

I guess this means I only have one file in the end (gradle.properties), so when I copy gradle.properties.no.git I will override?

**Comment by NiklasMoller** [comment]
I'm confused since we ask Travis to look for gradle.properties.no.git
 
    _- cp $TRAVIS_BUILD_DIR/android/gradle.properties.no.git $TRAVIS_BUILD_DIR/android/gradle.properties
 
    - sed -i "s/mykey/$API_KEY/g" $TRAVIS_BUILD_DIR/android/gradle.properties_
@platisd

**Comment by platisd** [comment]
Your version control system, knows only of `gradle.properties.no.git`, correct?
`gradle` knows only of `gradle.properties`, correct?

So Travis creates a copy `gradle.properties.no.git` (which contains no secrets) which it names `gradle.properties` (so `gradle` can use it). Then Travis replaces the dummy keys (i.e. `mykey` and `mysecret`) with the actual API secret and API key with the (encrypted) environment variables that you have to set via the [Travis settings page](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings). You need to do this replacement step only if you want Travis to run the app and let it connect to Google Maps if you want to test some functionality. If you just want it to compile you can ignore the two `sed` commands all together (but not the copying step).

**Pull request merged**
